### ISSUE TITLE
How to get a SVG string?

### ISSUE THREAD

**Issue by atmoio** [ap4y/UIBezierPath-SVG#3]
How are you getting your SVG strings? Currently if I open an SVG in a text editor, I get some XML/HTML formatted string, but your strings are completely different.

**Comment by ap4y** [comment]
You should search for a `<path>` tag inside your `svg` file, attribute name `d`. Hope this will help

**Comment by atmoio** [comment]
Thanks, this worked. This framework is great.

**Comment by ap4y** [comment]
Thanks, glad it helped.
